apiVersion : apps/v1
kind: Deployment
metadata:
  name: fareapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fareapp
  template:
    metadata:
      labels:
        app: fareapp
    spec:
      containers:
        - name: fareapp 
          image: myacr6bea8344.azurecr.io/fareapp
          ports:
          - containerPort: 8080
  ---
apiVersion: v1
kind: Service
metadata:
    name: fareapp
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: fareapp
